import pandas as pd
import sqlite3

def run_etl():
    print("Starting ETL process...")
    
    # 1. Load the CSV
    df = pd.read_csv('sensor_data.csv')
    
    # Ensure chronological order for accurate time-series calculations
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values('timestamp').reset_index(drop=True)
    
    # 2. Rolling window features (5-minute moving average)
    # Since Phase 1 generated exactly 1 row per minute, a window of 5 rows = 5 minutes
    df['temp_5min_ma'] = df['temperature_c'].rolling(window=5).mean()
    df['pressure_5min_ma'] = df['pressure_kpa'].rolling(window=5).mean()
    
    # 3. Rate of change (gradient) for mass of impurities (M)
    # diff() calculates the change in mass from the previous minute to the current minute
    df['impurity_mass_gradient'] = df['impurity_mass_g'].diff()
    
    # 4. Clean null values
    # The rolling window and diff create NaN values in the first few rows, so we drop them
    initial_rows = len(df)
    df = df.dropna().reset_index(drop=True)
    print(f"Dropped {initial_rows - len(df)} rows containing null values generated by rolling calculations.")
    
    # 5. Load processed data into local SQLite database
    db_name = 'sensor_database.db'
    table_name = 'sensor_features'
    
    print(f"Connecting to SQLite database: {db_name}...")
    with sqlite3.connect(db_name) as conn:
        # if_exists='replace' ensures we can safely re-run this script without duplicating data
        df.to_sql(table_name, conn, if_exists='replace', index=False)
        
    print(f"Success! {len(df)} engineered rows loaded into the '{table_name}' table.")

if __name__ == "__main__":
    run_etl()