# ---
# jupyter:
#   jupytext:
#     formats: py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.4
#   kernelspec:
#     display_name: Python 3 (ipykernel)
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Industrial IoT Sensor Analytics Pipeline
#
# This notebook outlines the automated ETL and machine learning process for predicting equipment anomalies before physical failure occurs.
#
# **Domain Constraints Enforced:**
# *   **Fluid Mechanics Setup:** The pipe length (L) is strictly standardized to 186 cm across all test cases to maintain experimental control.
# *   **Distillation Supply:** The parameter M explicitly represents the mass of impurities, which is used alongside molecular weight to dynamically calculate moles.

# %%
import pandas as pd
import sqlite3

def run_etl():
    print("Starting ETL process...")
    
    # 1. Load the CSV
    df = pd.read_csv('sensor_data.csv')
    
    # Ensure chronological order for accurate time-series calculations
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df = df.sort_values('timestamp').reset_index(drop=True)
    
    # 2. Rolling window features (5-minute moving average)
    # Since Phase 1 generated exactly 1 row per minute, a window of 5 rows = 5 minutes
    df['temp_5min_ma'] = df['temperature_c'].rolling(window=5).mean()
    df['pressure_5min_ma'] = df['pressure_kpa'].rolling(window=5).mean()
    
    # 3. Rate of change (gradient) for mass of impurities (M)
    # diff() calculates the change in mass from the previous minute to the current minute
    df['impurity_mass_gradient'] = df['impurity_mass_g'].diff()
    
    # 4. Clean null values
    # The rolling window and diff create NaN values in the first few rows, so we drop them
    initial_rows = len(df)
    df = df.dropna().reset_index(drop=True)
    print(f"Dropped {initial_rows - len(df)} rows containing null values generated by rolling calculations.")
    
    # 5. Load processed data into local SQLite database
    db_name = 'sensor_database.db'
    table_name = 'sensor_features'
    
    print(f"Connecting to SQLite database: {db_name}...")
    with sqlite3.connect(db_name) as conn:
        # if_exists='replace' ensures we can safely re-run this script without duplicating data
        df.to_sql(table_name, conn, if_exists='replace', index=False)
        
    print(f"Success! {len(df)} engineered rows loaded into the '{table_name}' table.")

if __name__ == "__main__":
    run_etl()

# %%
import sqlite3
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

def train_and_evaluate():
    print("Loading data from SQLite database...")
    
    # 1. Connect to the database and query the features
    db_name = 'sensor_database.db'
    with sqlite3.connect(db_name) as conn:
        df = pd.read_sql_query("SELECT * FROM sensor_features", conn)
        
    print(f"Dataset loaded successfully with {len(df)} rows.")

    # 2. Define Features (X) and Target (y)
    # We drop the timestamp (not a numeric feature) and our target label
    # Notice we are including the specific physical constraint (pipe_length_cm) 
    # and our engineered features (temp_5min_ma, pressure_5min_ma, impurity_mass_gradient)
    X = df.drop(columns=['timestamp', 'anomaly_detected'])
    y = df['anomaly_detected']

    # 3. Split the data (80% training, 20% testing)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    print(f"Training set: {len(X_train)} rows | Testing set: {len(X_test)} rows")

    # 4. Initialize and Train the Model
    print("\nTraining Logistic Regression model...")
    # max_iter=1000 ensures the gradient descent converges properly
    model = LogisticRegression(max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    # 5. Predict and Evaluate
    print("Evaluating model performance on test data:\n")
    y_pred = model.predict(X_test)
    
    # The classification report shows Precision, Recall, and F1-Score
    report = classification_report(y_test, y_pred, target_names=["Normal (0)", "Anomaly (1)"])
    print(report)

if __name__ == "__main__":
    train_and_evaluate()

# %%
